### ISSUE TITLE
Could not generate report: java.nio.charset.MalformedInputException: Input length = 1

### ISSUE THREAD

**Issue by florin-talarian** [simple-elf/allure-report-action#25]
Starting with this weekend I have this error popup randomly when generating the allure reports. 
```
Run simple-elf/allure-report-action@master
  with:
    allure_results: allure-results
    allure_history: allure-history
    keep_reports: [2](https://github.com/ScriptAddicts/yamm-addon-regression/runs/5473113188?check_suite_focus=true#step:15:2)0
    allure_report: allure-report
    gh_pages: gh-pages
    github_run_num: 204
    github_run_id: 195452[3](https://github.com/ScriptAddicts/yamm-addon-regression/runs/5473113188?check_suite_focus=true#step:15:3)7[4](https://github.com/ScriptAddicts/yamm-addon-regression/runs/5473113188?check_suite_focus=true#step:15:4)6
    github_repo: ScriptAddicts/yamm-addon-regression
    github_repo_owner: ScriptAddicts
  env:
    FORCE_COLOR: 1
    NODE_AUTH_TOKEN: ***
/usr/bin/docker run --name fb7a2dc3c608df24b14326aba11a06240ffbbf_87bf01 --label fb7a2d --workdir /github/workspace --rm -e FORCE_COLOR -e NODE_AUTH_TOKEN -e INPUT_ALLURE_RESULTS -e INPUT_ALLURE_HISTORY -e INPUT_KEEP_REPORTS -e INPUT_ALLURE_REPORT -e INPUT_GH_PAGES -e INPUT_SUBFOLDER -e INPUT_GITHUB_RUN_NUM -e INPUT_GITHUB_RUN_ID -e INPUT_GITHUB_REPO -e INPUT_GITHUB_REPO_OWNER -e INPUT_REPORT_URL -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/florin/actions-runner/_work/_temp/_github_home":"/github/home" -v "/home/florin/actions-runner/_work/_temp/_github_workflow":"/github/workflow" -v "/home/florin/actions-runner/_work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/florin/actions-runner/_work/yamm-addon-regression/yamm-addon-regression":"/github/workspace" fb7a2d:c3c608df24b14326aba11a06240ffbbf
count folders in allure-history: 3
keep reports count 20
if 3 > 21
keep allure history from gh-pages/last-history to allure-results/history
generating report from allure-results to allure-report ...
Could not generate report
java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:28[5](https://github.com/ScriptAddicts/yamm-addon-regression/runs/5473113188?check_suite_focus=true#step:15:5))
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
	at java.io.BufferedWriter.close(BufferedWriter.java:2[6](https://github.com/ScriptAddicts/yamm-addon-regression/runs/5473113188?check_suite_focus=true#step:15:6)5)
	at io.qameta.allure.CommonCsvExportAggregator.aggregate(CommonCsvExportAggregator.java:69)
	at io.qameta.allure.CompositeAggregator.aggregate(CompositeAggregator.java:43)
	at io.qameta.allure.ReportGenerator.aggregate(ReportGenerator.java:53)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:[7](https://github.com/ScriptAddicts/yamm-addon-regression/runs/5473113188?check_suite_focus=true#step:15:7)0)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:5[8](https://github.com/ScriptAddicts/yamm-addon-regression/runs/5473113188?check_suite_focus=true#step:15:8))
	at io.qameta.allure.Commands.generate(Commands.java:[10](https://github.com/ScriptAddicts/yamm-addon-regression/runs/5473113188?check_suite_focus=true#step:15:10)4)
	at io.qameta.allure.CommandLine.run(CommandLine.java:[15](https://github.com/ScriptAddicts/yamm-addon-regression/runs/5473113188?check_suite_focus=true#step:15:15)2)
	at java.util.Optional.orElseGet(Optional.java:267)
	at io.qameta.allure.CommandLine.main(CommandLine.java:88)
copy allure-report to allure-history/[20](https://github.com/ScriptAddicts/yamm-addon-regression/runs/5473113188?check_suite_focus=true#step:15:20)4
copy allure-report history to /allure-history/last-history
```

Is this related to [allure-report-action](https://github.com/simple-elf/allure-report-action) or with allure itself? Not sure where to put the issue. Thanks

**Comment by mgrybyk** [comment]
Are you able to generate report locally?
